facets.facet_source.*:
  type: config_entity
  label : 'Facet Source'
  mapping:
    uuid:
      type: string
      label: 'UUID'
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: Name'
    filterKey:
      type: string
      label: 'Filter key'
    url_processor:
      type: string
      label: 'Url processor'
