# Default config schema that all widgets can extend.
facet.widget.default_config:
  type: mapping
  label: 'Default widget configuration'
  mapping:
    show_numbers:
      type: boolean
      label: 'Show counts'

# Default schema for facet widgets of unknown type.
facet.widget.config.*:
  type: facet.widget.default_config

# Config schema for dropdown, you can find the implementation in
# Drupal\facets\Plugin\facets\widget\DropdownWidget. Options for this widget are
# "show counts" and "default option label".
facet.widget.config.dropdown:
  type: facet.widget.default_config
  label: 'Dropdown widget configuration'
  mapping:
    default_option_label:
      type: string
      label: 'Default option label'

# Config schema for links, you can find the implementation in
# Drupal\facets\Plugin\facets\widget\LinksWidget. Options for this widget are
# "soft limit" and "show counts".
facet.widget.config.links:
  type: facet.widget.default_config
  label: 'List of links widget configuration'
  mapping:
    soft_limit:
      type: integer
      label: 'Soft limit'

# Config schema for slider, you can find the implementation in
# Drupal\facets\Plugin\facets\widget\SliderWidget.
facet.widget.config.slider:
  type: facet.widget.default_config
  label: 'List of range widget configuration'
  mapping:
    prefix:
      type: string
      label: 'Prefix'
    suffix:
      type: string
      label: 'Suffix'
    min_type:
      type: string
      label: 'Minimum type'
    min_value:
      type: float
      label: 'Minimum value'
    max_type:
      type: string
      label: 'Maximum type'
    max_value:
      type: float
      label: 'Maximum value'
    step:
      type: float
      label: 'Step'

# Config schema for checkbox, you can find the implementation in
# Drupal\facets\Plugin\facets\widget\CheckboxWidget. Options for this widget are
# "soft limit" and "show counts".
facet.widget.config.checkbox:
  type: facet.widget.config.links
