plugin.plugin_configuration.facets_processor.count_widget_widget_order:
  type: mapping
  label: 'Count widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.display_value_widget_order:
  type: mapping
  label: 'Display value widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.raw_value_widget_order:
  type: mapping
  label: 'Raw value widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.active_widget_order:
  type: mapping
  label: 'Active widget order'
  mapping:
    sort:
      type: string
      label: sort order

plugin.plugin_configuration.facets_processor.count_limit:
  type: mapping
  label: 'Count limit widget'
  mapping:
    minimum_items:
      type: integer
      label: 'Mimimum amount of items to show.'
    maximum_items:
      type: integer
      label: 'Maximum amount of items to show.'

# There are no settings intended for this, this will probably always be an empty
# array but not having a schema available means the facet config is not correct.
# This is important because the tests use strict config validation.
plugin.plugin_configuration.facets_processor.url_processor_handler:
  type: sequence
  label: 'URL processor settings'
  sequence:
    type: string
    label: 'Single settings'
